//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.itianchuang.Web.video_file {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblfile_name;
	protected global::System.Web.UI.WebControls.Label lblfile_type;
	protected global::System.Web.UI.WebControls.Label lblfile_path;
	protected global::System.Web.UI.WebControls.Label lblfile_size;
	protected global::System.Web.UI.WebControls.Label lblstart_time;
	protected global::System.Web.UI.WebControls.Label lblend_time;
	protected global::System.Web.UI.WebControls.Label lblfk_device;
	protected global::System.Web.UI.WebControls.Label lblis_value;


       
    }
}
